
#include <stdio.h>
#include <stdlib.h>
#include <termios.h>
#include <unistd.h>
#include <fcntl.h>
#include <string.h>
#include <sys/stat.h>

#include "libcurvetr.h"

// WARNING: This is a quickdirty hack. There is no error handling at all!
// Use the UNIX command 'strace' in case it does not work..

int serfd;

void libcurvetr_setup(const char *serdev)
{
	struct termios tio;
	serfd = open(serdev, O_RDWR);
	memset(&tio, 0, sizeof(tio));
	tcgetattr(serfd, &tio);
	cfsetospeed(&tio, B38400);
	tcsetattr(serfd, TCSANOW, &tio);
}

void libcurvetr_shutdown()
{
	close(serfd);
}

void libcurvetr_getraw(int v[6])
{
	char buffer[100], *p;
	int i, rc;

	do {
		i = 0;
		p = buffer;
		while (i < 6*4+3) {
			rc = read(serfd, p+i, (6*4+3) - i);
			if (rc > 0) {
				i += rc;
				while (i > 0 && *p != ':')
					p = (--i) == 0 ? buffer : p+1;
			}
		}
	} while (p[6*4+1] != '\r' || p[6*4+2] != '\n');

	for (i = 0; i < 6; i++)
		v[i] = strtol(p + i*4 + 2, NULL, 16);
}

void libcurvetr_getvolt(double v[6])
{
	int i, iv[6];
	libcurvetr_getraw(iv);
	for (i = 0; i < 6; i++) {
		// as generated by libcurvetr_calib()
		v[i] = 0.004922 * iv[i] + 0.003693;
	}
}

int libcurvetr_gotkey()
{
	int ret;
	char buffer[16];
	fcntl(0, F_SETFL, fcntl(0, F_GETFL) | O_NONBLOCK);
	ret = read(0, buffer, 16) > 0;
	fcntl(0, F_SETFL, fcntl(0, F_GETFL) & ~O_NONBLOCK);
	return ret;
}

#if 0
void libcurvetr_calib()
{
	int i, j, k, v[6];
	double cv[51];

	for (i = 0; i <= 50; i++)
	{
		printf("Apply %d.%dV and press ENTER..", i/10, i%10);
		fflush(stdout);

		while (!libcurvetr_gotkey())
			libcurvetr_getraw(v);

		cv[i] = 0;
		for (j = 0; j < 10; j++) {
			libcurvetr_getraw(v);
			for (k = 0; k < 6; k++)
				cv[i] += v[k] / 60.0;
		}
	}

	printf("double calib_data[51] = {");
	for (i = 0; i <= 50; i++)
		printf("%s%.2f%s", i%12 == 0 ? "\n\t" : " ", cv[i], i != 50 ? "," : "");
	printf("\n};\n");
}
#endif

#if 1
void libcurvetr_calib()
{
	double x1, x4, y1, y4, k, d;
	int i, j, v[6];

	printf("Apply about 1V and press ENTER..");
	fflush(stdout);

	while (!libcurvetr_gotkey())
		libcurvetr_getraw(v);

	x1 = 0;
	for (i = 0; i < 100; i++) {
		libcurvetr_getraw(v);
		for (j = 0; j < 6; j++)
			x1 += v[j] / 600.0;
	}

	do {
		printf("Enter the exact voltage: ");
		fflush(stdout);
	} while (scanf("%lf", &y1) != 1);

	printf("Apply 4V and press ENTER..");
	fflush(stdout);

	while (!libcurvetr_gotkey())
		libcurvetr_getraw(v);

	x4 = 0;
	for (i = 0; i < 100; i++) {
		libcurvetr_getraw(v);
		for (j = 0; j < 6; j++)
			x4 += v[j] / 600.0;
	}

	do {
		printf("Enter the exact voltage: ");
		fflush(stdout);
	} while (scanf("%lf", &y4) != 1);

	// y = k*x + d
	k = (y4 - y1) / (x4 - x1);
	d = y1 - k*x1;

	printf("v[i] = %f * iv[i] + %f;\n", k, d);
}
#endif

