all: permexplore permfind permrvcj

permexplore: permexplore.cc permdb.h
	g++ -o permexplore -Wall -Werror -O3 -march=native permexplore.cc

permfind: permfind.cc permdb.h
	g++ -o permfind -Wall -Werror -O3 -march=native permfind.cc

permrvcj: permrvcj.cc permdb.h
	g++ -o permrvcj -Wall -Werror -O3 -march=native permrvcj.cc
