
// cell types for raw nmos netlist

module SW(input gate, inout cc1, inout cc2);
endmodule

module SW0(input gate, output cc);
endmodule

module SW1(input gate, output cc);
endmodule

module PULLUP(output y);
endmodule

// cell types generated by sw2sr pass

module SR(input S, input R, output Q);
endmodule

